//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ##DESIGNATION_NAME## designation is now active..
        /// </summary>
        public static string DESIGNATION_ACTIVE_STATUS_MESSAGE {
            get {
                return ResourceManager.GetString("DESIGNATION_ACTIVE_STATUS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add this designation?.
        /// </summary>
        public static string DESIGNATION_ADD_CONFIRM_MESSGAE {
            get {
                return ResourceManager.GetString("DESIGNATION_ADD_CONFIRM_MESSGAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Designation Confirmation.
        /// </summary>
        public static string DESIGNATION_ADD_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("DESIGNATION_ADD_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designation has been successfully added..
        /// </summary>
        public static string DESIGNATION_ADD_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("DESIGNATION_ADD_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ##DESIGNATION_NAME## designation has been deactivated..
        /// </summary>
        public static string DESIGNATION_DEACTIVE_STATUS_MESSAGE {
            get {
                return ResourceManager.GetString("DESIGNATION_DEACTIVE_STATUS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Designation Confirmation.
        /// </summary>
        public static string DESIGNATION_DELETE_CONFIRM_MESSAGE {
            get {
                return ResourceManager.GetString("DESIGNATION_DELETE_CONFIRM_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you certain you want to delete this designation?.
        /// </summary>
        public static string DESIGNATION_DELETE_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("DESIGNATION_DELETE_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update the status?.
        /// </summary>
        public static string DESIGNATION_STATUS_CAHNGE_MESSAGE {
            get {
                return ResourceManager.GetString("DESIGNATION_STATUS_CAHNGE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Status Update Confirmation.
        /// </summary>
        public static string DESIGNATION_STATUS_CAHNGE_TITLE {
            get {
                return ResourceManager.GetString("DESIGNATION_STATUS_CAHNGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update this designation?.
        /// </summary>
        public static string DESIGNATION_UPDATE_CONFIRM_MESSGAE {
            get {
                return ResourceManager.GetString("DESIGNATION_UPDATE_CONFIRM_MESSGAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Designation Confirmation.
        /// </summary>
        public static string DESIGNATION_UPDATE_CONFIRM_TITLE {
            get {
                return ResourceManager.GetString("DESIGNATION_UPDATE_CONFIRM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The designation has been successfully updated..
        /// </summary>
        public static string DESIGNATION_UPDATE_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("DESIGNATION_UPDATE_SUCCESS_MESSAGE", resourceCulture);
            }
        }
    }
}
